import ATM.ATMDemo;
import AirlineManagementSystem.AirlineManagementSystemDemo;
import AuctionSystem.AuctionSystemDemo;
import CarRentalSystem.CarRentalSystemDemo;
import ChessGame.ChessGameDemo;
import CoffeeVendingMachine.CoffeeVendingMachineDemo;
import ConcertTicketBookingSystem.ConcertTicketBookingSystemDemo;
import CourseRegistrationSystem.CourseRegistrationSystemDemo;
import Cricinfo.CricinfoDemo;
import DigitalWallet.DigitalWalletDemo;
import ElevatorSystem.ElevatorSystemDemo;
import FoodDeliveryService.FoodDeliveryServiceDemo;
import HotelManagementSystem.HotelManagementSystemDemo;
import LRUCache.LRUCacheDemo;
import LibraryManagementSystem.LibraryManagementSystemDemo;
import LinkedIn.LinkedInDemo;
import LoggingFramework.LoggingFrameworkDemo;
import MovieTicketBooking.MovieTicketBookingDemo;
import MusicStreamingService.MusicStreamingServiceDemo;
import OnlineShoppingService.OnlineShoppingServiceDemo;
import ParkingLot.ParkingLotDemo;
import PubSubSystem.PubSubSystemDemo;
import RestaurantManagement.RestaurantManagementDemo;
import RideSharingService.RideSharingServiceDemo;
import SnakeAndLadder.SnakeAndLadderDemo;
import SocialNetworkingService.SocialNetworkingServiceDemo;
import Splitwise.SplitwiseDemo;
import StackOverflow.StackOverflowDemo;
import StockBrokerageSystem.StockBrokerageSystemDemo;
import TaskManagementSystem.TaskManagementSystemDemo;
import TicTacToe.TicTacToeDemo;
import TrafficSignalSystem.TrafficSignalSystemDemo;
import VendingMachine.VendingMachineDemo;
import VotingSystem.VotingSystemDemo;

public class LLDMasterRunner {
    public static void main(String[] args) {
        AirlineManagementSystemDemo.run();
        ATMDemo.run();
        CarRentalSystemDemo.run();
        ChessGameDemo.run();
        CoffeeVendingMachineDemo.run();
        ConcertTicketBookingSystemDemo.run();
        CourseRegistrationSystemDemo.run();
        CricinfoDemo.run();
        DigitalWalletDemo.run();
        ElevatorSystemDemo.run();
        FoodDeliveryServiceDemo.run();
        HotelManagementSystemDemo.run();
        LibraryManagementSystemDemo.run();
        LinkedInDemo.run();
        LoggingFrameworkDemo.run();
        LRUCacheDemo.run();
        MovieTicketBookingDemo.run();
        MusicStreamingServiceDemo.run();
        AuctionSystemDemo.run();
        OnlineShoppingServiceDemo.run();
        StockBrokerageSystemDemo.run();
        ParkingLotDemo.run();
        PubSubSystemDemo.run();
        RestaurantManagementDemo.run();
        RideSharingServiceDemo.run();
        SnakeAndLadderDemo.run();
        SocialNetworkingServiceDemo.run();
        SplitwiseDemo.run();
        StackOverflowDemo.run();
        TaskManagementSystemDemo.run();
        TicTacToeDemo.run();
        TrafficSignalSystemDemo.run();
        VendingMachineDemo.run();
        VotingSystemDemo.run();
    }

}
