public class LLDMasterRunner {
    public static void main(String[] args) {
       AirlineManagementSystemDemo.run();
       ATMDemo.run();
       CarRentalSystemDemo.run();
       ChessGameDemo.run();
       CoffeeVendingMachineDemo.run();
       ConcertTicketBookingSystemDemo.run();
       CourseRegistrationSystemDemo.run();
       CricinfoDemo.run();
       DigitalWalletDemo.run();
       ElevatorSystemDemo.run();
       FoodDeliveryServiceDemo.run();
       HotelManagementSystemDemo.run();
       LibraryManagementSystemDemo.run();
       LinkedInDemo.run();
       LoggingFrameworkDemo.run();
       LRUCacheDemo.run();
       MovieTicketBookingDemo.run();
       MusicStreamingServiceDemo.run();
       AuctionSystemDemo.run();
       OnlineShoppingServiceDemo.run();
       StockBrokerageSystemDemo.run();
       ParkingLotDemo.run();
       PubSubSystemDemo.run();
       RestaurantManagementDemo.run();
       RideSharingServiceDemo.run();
       SnakeAndLadderDemo.run();
       SocialNetworkingServiceDemo.run();
       SplitwiseDemo.run();
       StackOverflowDemo.run();
       TaskManagementSystemDemo.run();
       TicTacToeDemo.run();
       TrafficSignalSystemDemo.run();
       VendingMachineDemo.run();
       VotingSystemDemo.run();
    }

}
